// One fun fact per element for the "Did You Know?" section on level complete

export const ELEMENT_FACTS: Record<number, string> = {
  1:  'Hydrogen makes up 75% of all normal matter in the universe by mass.',
  2:  'Helium was first discovered in the spectrum of the Sun before being found on Earth.',
  3:  'Lithium is the lightest metal and floats on water.',
  4:  "Beryllium is transparent to X-rays and is used in X-ray machine windows.",
  5:  "Boron is essential for plant growth but toxic to plants in excess.",
  6:  "Carbon can form 4 covalent bonds, enabling over 10 million known organic compounds.",
  7:  "Nitrogen makes up 78% of Earth's atmosphere — every breath is mostly N\u2082.",
  8:  "Oxygen is the third most abundant element in the universe, forged in stellar cores.",
  9:  'Fluorine is the most reactive element — it reacts with almost everything, including noble gases.',
  10: 'Neon signs glow red-orange. Other colors come from different gases or phosphor coatings.',
  11: "Sodium reacts violently with water. It's stored in oil to prevent contact with air moisture.",
  12: 'Magnesium burns with a brilliant white flame and is used in fireworks and flares.',
  13: "Aluminium is the most abundant metal in Earth's crust at 8% by mass.",
  14: 'Silicon is the backbone of modern computing — every processor chip is built from it.',
  15: 'Phosphorus was discovered by an alchemist boiling urine — it glows in the dark.',
  16: "Sulfur's distinctive smell comes from its compounds, not pure sulfur (which is odorless).",
  17: 'Chlorine was used as a chemical weapon in WWI before becoming a water purifier.',
  18: "Argon fills incandescent light bulbs to prevent the tungsten filament from oxidizing.",
  19: "Potassium is essential for nerve function. Bananas are famously (but mildly) radioactive due to K-40.",
  20: "Calcium makes up 2% of human body weight — mostly in bones and teeth.",
  21: 'Scandium is used in aerospace alloys. Scandium-aluminium alloys are lighter than titanium.',
  22: 'Titanium has the highest strength-to-weight ratio of any metallic element.',
  23: "Vanadium steel is so tough it was used in Henry Ford's Model T chassis.",
  24: "Chromium's name comes from Greek 'chroma' (color) — its compounds produce vivid pigments.",
  25: 'Manganese is essential for photosynthesis — it helps split water molecules in plants.',
  26: 'Iron is forged in the cores of massive stars and scattered across the cosmos by supernovae.',
  27: 'Cobalt gives a distinctive deep blue color to glass and ceramics — used since antiquity.',
  28: "Nickel is one of only four elements that are ferromagnetic at room temperature.",
  29: 'Copper was the first metal used by humans, dating back over 10,000 years.',
  30: "Zinc coatings (galvanization) protect steel from rust — the Statue of Liberty's framework is zinc-coated.",
  31: "Gallium melts at 29.76\u00B0C — it will literally melt in your hand.",
  32: 'Germanium was predicted by Mendeleev in 1871 as "eka-silicon" and discovered 15 years later.',
  33: 'Arsenic was historically called "inheritance powder" due to its use in poisoning.',
  34: 'Selenium is named after the Moon (Greek: Selene) and is essential for human health in trace amounts.',
  35: 'Bromine is one of only two elements that are liquid at room temperature (the other is mercury).',
  36: 'Krypton — yes, like Superman — is used in high-performance photographic flash lamps.',
};
